common: &common
  adapter: mysql2
  encoding: utf8
  username: root
  host: localhost

development: 
  <<: *common
  database: hevix_development

test: 
  <<: *common
  database: hevix_test

production: 
  <<: *common
  database: hevix_production
